<?php
load_view("Template/top.php",$inp);
load_view("Template/navbarnew.php",$inp);
?>		
		<div class="container" id="container">
			<div class="card-panel">
					
				<div>
					<h3 class="header center teal-text">Terms of Use<hr></h3>
					<div class="row center">
						<p>Welcome, and thank you for your interest in GetIITians, which operates the website at http://getiitians.com and related application programming interfaces (API’s), mobile applications and online services (the website).Visitors and users of the website are referred to individually as “User” and collectively as “Users”.</p><br><hr>
						<p><b>PLEASE READ THE FOLLOWING TERMS OF SERVICE CAREFULLY. BY REGISTERING OR ACCESSING OR BROWSING, OR USING THE WEBSITE, YOU ACKNOWLWDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THE FOLLOWING TERMS AND CONDITIONS, INCLUDING THE GETIITIANS PRIVACY NOTICE AND ANY CONDITIONAL GUIDELINES (AS DEFINED BELOW)(COLLECTIVELY , THE “TERMS”).</b></p><br><hr>
					</div>
				</div>
				<div class="row center">
					<h4 style="color:teal;">Contents</h4>
					<p>IF YOU ARE A PARENT OR GUARDIAN AND YOU PROVIDE CONSENT FOR YOUR CHILD TO REGISTER WITH THE WEBSITE, YOU AGREE TO BE BOUND BY THESE TERMS OF SERVICE IN RESPECT OF SUCH CHILD’S USE OF THE WEBSITE.</p>
				</div>
				<div>
					<ul class="collapsible" data-collapsible="accordion">
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Acceptance of Terms</b></div>
							<div class="collapsible-body"><p>By clicking "I Agree" on the account registration page or payment page or submission page or using the Site in any way, you are agreeing to comply with and be bound by this submission page or agreement, the Privacy Policy and all rules, policies and disclaimers posted on the Site or about which you are notified. Your agreement shown by accessing and using this website is legally binding. If you do not agree to all these terms and conditions, do not access this website.
							If you are an individual entering into this Agreement on behalf of a company or other legal entity, you represent that you have the authority to bind such entity to this Agreement. If you do not agree with each provision of this Agreement, or you are not authorized to enter into this Agreement, you may not enter into the Agreement or use the service.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Eigibility of Use</b></div>
							<div class="collapsible-body"><p>Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. Persons under the age of 18 may use this Site and submit personal information to us only in conjunction with and under the supervision of their parents or guardians. The user of this site by a person under the age of 18 constitutes the agreement of the parent or guardian to see these Terms and Conditions</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Definitions</b></div>
							<div class="collapsible-body"><p>In the terms, “User”, “you”, and “your” refer to the individual or entity that creates a GetIITians account as a customer and/or Tutors. “GetIITians”, “we”, “us” and “our” refers to GetIITians. “Customer refers to the person who buys and books time slot on our site. “Tutor” refers to the person who teaches the “Customer” according to the pre-booked time by the “Customer”. They both are marginally different but both use website resources.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Right to Modify Terms</b></div>
							<div class="collapsible-body"><p>When you visit getiitians.com or send us e-mails, you are communicating with us thorough electronic media. You consent to receive communications from us electronically. We will communicate with you by e-mails or chats or pop-ups, by posting notices anywhere on website getiitians.com. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. You agree to provide us with, and maintain in your getIITians account profile, your current and active email address. If the account has been terminated by you or us or you file a request of changing your email address, the claims on all past interactions with us on the previous email address will be invalid and will be treated as User not subjected to getIITians. 
							If you do not accept the changes, your sole and exclusive remedy is to discontinue using the Site. GetIITians reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) or prices with or without notice. You agree that getIITians shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.
							We may change these terms and conditions, and you are responsible for regularly reviewing and complying with them. Your continued use of this website constitutes your agreement to all those terms and conditions.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Description of Services:</b></div>
							<div class="collapsible-body"><p>The service consists of the provision by getIITians to you of access to the getIITians site, which provides tools to you that will enable you to study/teach online, take online tests, free demos, participate in online discussions, create online communities pertaining to specific topics, create lessons (comprised os text, images, video, flash), create tests, create and administer online educational course(s), create and administer synchronous online tutoring, offer courses and online tutoring services for sale via an online interface. Unless explicitly stated otherwise, any new features that augment or enhance the current service shall be subject to the terms and conditions of this Agreement. The service may not be used for any purpose not expressly permitted by this Agreement. You may not reproduce, copy, sell, or resell any part of the service. GetIITians owns no responsibility in any manner over any dispute arising out of transactions by any third party using your account/e-mail provided by you to GetIITians or payments made by any of the payment methods by any third party.  We make no representation that any products or services referred to in the materials on this web are appropriate for use, or available outside India. Those who choose to access this Website from outside India are responsible for compliance with local laws if and to the extent local laws are applicable.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Accuracy of Contents</b></div>
							<div class="collapsible-body"><p>We have taken every care in the preparation of the content of this Website. To the extent permitted by applicable law, we disclaim all warranties, express or implied, as to the accuracy of the information contained in any of the materials on this Website. We shall not be liable to any person for any loss or damage which may arise from the use of any of the information contained in any of the materials on this Website.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Account and Registration Obligations</b></div>
							<div class="collapsible-body"><p>In consideration of your use of our Website, you represent that you are of legal age to form a binding contract and are not a person barred from receiving services under the laws as applicable in India. You also agree to provide true, accurate, current and complete information about yourself as prompted by our Website’s registration form or any information provided by you by other means of communication.. If you provide any information that is untrue, inaccurate, not current or incomplete (or becomes untrue, inaccurate, not current or incomplete), or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of our Website (or any portion thereof).  You undertake to indemnify and keep indemnified GetIItians for any loss, claim, damage, costs (including legal and professional costs) relating to any abuse or violation including those aforesaid.<br>
							"Your Information" is defined as any information you provide to us in the registration, buying or listing process, in the feedback area or through any email feature. We will protect Your Information in accordance with our Privacy Policy. If you use the Site, you are responsible for maintaining the confidentiality of Your Login ID and Password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under Your Login ID or Password. We shall not be liable to any person for any loss or damage which may arise as a result of any failure by you to protect your password or account. You undertake to indemnify and keep indemnified getIITians for any loss, claim, damage, costs (including legal and professional costs) relating to your responsibility or liability or failure including those aforesaid. You agree to notify us immediately of any unauthorized use of your account or any other breach of security. We reserve the right to refuse service, terminate accounts, or remove or edit content in its sole discretion.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Credit Card/Debit Card Details</b></div>
							<div class="collapsible-body"><p>You agree, understand and confirm that the credit card details provided by you for availing of services on our Website will be correct and accurate and you shall not use the credit card/debit card which is not lawfully owned by you, i.e. in a transaction, you must use your own card/account. You further agree and undertake to provide the correct and valid credit card details when making payment on our Website. We do not store any information related to your Credit card/ Debit card or net banking. In case we do not receive an authorization from the respective bank or the transaction gets interrupted due to any reason, the transaction will be treated as failed and no order will be processed for that transaction. In this case, if any amount has been deducted from your account, the same will be credited back. We shall not be liable in any event, for any credit card fraud that occurs to you. The liability for use of a card fraudulently will be on you and the onus to 'prove otherwise' shall be exclusively on you.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Fraudulent/Declined Transactions</b></div>
							<div class="collapsible-body"><p>Our payment partner’s (being the Payment Gateways and facilitators and Banks) and our fraud detection team constantly monitors your account in order to avoid fraudulent accounts and transactions. We reserve the right to initiate legal proceedings against such persons for fraudulent use of our Website and any other unlawful acts or omissions in breach of these terms and conditions. In the event of detection of any fraudulent or declined transaction, prior to initiation of legal actions, we reserve the right to immediately delete such user account(s) and dishonour all past and pending orders without any liability. For the purpose of this clause, we shall owe no liability for any refunds.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>SMS Communication</b></div>
							<div class="collapsible-body"><p>On registering in our website, you agree that we may use your registered mobile number on the Website to send Transaction related SMS to you. You also grant us permission that we may send you any Transaction related SMS irrespective of having DND services activated on your mobile.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Services Provided by Third Party</b></div>
							<div class="collapsible-body"><p>The user hereby agrees and understands that the services provided by GetIITians also include such exclusive third party services. The user admits that the use of such third party services shall be the sole responsibility of the user and the user shall ensure that he/she maintains such telecommunications and internet services necessary for availing such services along with such required software and hardware devices, at the sole cost of the user. The user hereby agrees and acknowledges that GetIITians shall not be liable for any loss, data corruption, bad signals, communication difficulties</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Abuse or Misuse of the Website</b></div>
							<div class="collapsible-body"><p>The user hereby agrees that the user shall neither by itself nor be part of any kind of abuse or misuse of the Website in any manner whatsoever. By availing to the online tutorial sessions through the Website, the user agrees that, apart from not sharing any kind of personal information of any kind with the other party, the user shall also ensure that he/she shall not inter-alia share, display, convey, transmit or portray abusive content of any kind in any manner whatsoever. Likewise, in the event the user feels that there is any kind of abusive content or such other information shared / displayed by the other party, the user shall immediately report the same to us at info@getiitians.com. In the event GetIITians has reasons to believe that the user is inter-alia sharing, displaying, conveying, transmitting or portraying abusive content of any kind of the user has been part of such transmission, GetIITians has the absolute right to terminate the account and the services availed by the user without providing any reason whatsoever, apart from other measures that GetIITians may recourse to. The user hereby also agrees and confirms that GetIITians shall not be responsible or liable for inter-alia any act as mentioned above in any manner whatsoever and that the user shall not make any kind of claim against GetIITians or make GetIITians party to any claim he/she is making before any forum in relation to any abuse or misuse of the Website to which the user is a party to or otherwise. The user hereby also agrees and understands that it shall be the sole responsibility of the user to restrict such abuse or misuse of any kind of the Website and the services availed and the user shall ensure that it shall report to GetIITians at the earliest on occurrence of any such event.<br>
							Similarly, the user hereby also agrees that he/she shall not inter-alia share, display or transmit any copyrighted material which he/she is not permitted to do in the course of the facilities availed of the Website. The user shall be entitled to share only such materials which have an open source code and that they have specifically permitted the user to share. In the event the user shares any of the copyrighted materials to the other party without the prior written consent of GetIITians, the user shall be liable for such actions taken against it by GetIITians and any aggrieved third party for violations of the intellectual property rights of such parties.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Refunds</b></div>
							<div class="collapsible-body"><P>You are not entitled to ask for refunds once you have used our services. In the     event you are not satisfied with the services provided by GetIITians or you have any complaints regarding our services, we request you to contact us at info@getiitians.com. The user hereby acknowledge that the final decision of refund of payments made by the user, will be at the sole discretion of GetIITians.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>You Agree and Confirm</b></div>
							<div class="collapsible-body"><p>
							<ol>
								<li>That you shall use the service provided by us, for lawful purpose only and shall comply with all applicable laws and regulations while using the Website and transacting the Website.</li>
								<li>You shall provide authentic and true information in all instances where such information is requested of you. We reserve the right to confirm and validate the information and other details provided by you at any point of time. If upon confirmation your details are found to be false (wholly or partly), we have the right and the sole discretion to reject the registration and debar you from using the services of our Website without prior intimation whatsoever.</li>
								<li>That you shall access the services available on this Website and transact at your sole risk and shall use your best and prudent judgment before entering into any transaction through this Website.</li>
								<li>That neither you nor the tutor shall share their respective personal details including any kind of contact information with each other. In the event the user becomes aware of any such information, the user shall intimate GetIITians on the same at the earliest. </li>
							</ol></p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>You agree and confirm that you shall not use our Website for any of the followingpurposes</b></div>
							<div class="collapsible-body"><p>
								<ol>
									<li>Disseminating any lawful, harassing, libellous, abusive, threatening, harmful, vulgar, obscene, or otherwise objectionable material.</li>
									<li>Transmitting material that encourages conduct that constitutes a criminal offence, results in civil liability or otherwise breaches any relevant laws, regulations or code of practice.</li>
									<li>Gaining unauthorized access to other computer systems.</li>
									<li>Using, displaying, mirroring or framing the Site, or any individual element within the Site or services, GetIITians’s name, any GetIItians trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without GetIITians’s express written consent.</li>
									<li>Interfering with any other person's use or enjoyment of the Site.</li>
									<li>Breaching any applicable laws, rules or regulations.</li>
									<li>Interfering or disrupting networks or web sites connected to the Site.</li>
									<li>Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the copyright owner.</li>
									<li>Collecting or storing any personally identifiable information from the Site or services from other users of the Site or services without their express permission.</li>
									<li>Impersonating or misrepresenting your affiliation with any person or entity.</li>
									<li>Violating any applicable law or regulation.</li>
									<li>Encouraging or enabling any other individual to do any of the foregoing.</li>
								</ol>
							</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Governing Law and Jurisdiction</b></div>
							<div class="collapsible-body"><p>These Terms shall be construed in accord with the applicable laws of India. The Courts at New Delhi shall have exclusive jurisdiction in any proceedings arising out of these Terms.
							In the event of any dispute or difference either in interpretation or otherwise, of any terms of these Terms of Use, the same shall be referred to an independent arbitrator who will be appointed by GetIItians and such Arbitrator’s decision shall be final and binding on you. The above arbitration shall be in accordance with the Arbitration and Conciliation Act, 1996 as amended time to time. The arbitration shall be held in New Delhi.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Reviews, Feedback ans Submission</b></div>
							<div class="collapsible-body"><p>All reviews, comments, feedback, postcards, suggestions, ideas, and other submissions disclosed, submitted or offered on or by our Website, submitted or offered in connection with your use of this Website (collectively, the "Comments") shall be and remain our property. Such disclosure, submission or offer of any Comments shall constitute an assignment to us of all worldwide rights, titles and interests in all copyrights and other intellectual properties in the Comments. Thus, we own exclusively all such rights, titles and interests and shall not be limited in any way in its use, commercial or otherwise, of any Comments. We will be entitled to use, reproduce, disclose, modify, adapt, create derivative works from, publish, display and distribute any Comments you submit for any purpose whatsoever, without restriction and without compensating you in any way. We are and shall be under no obligation (1) to maintain any Comments in confidence; (2) to pay you any compensation for any Comments of use of comments; or (3) to respond to any Comments. You agree that any Comments submitted by you to our Website shall not violate this policy or any right of any third party, including copyright, trademark, privacy or other personal or proprietary right(s), and shall not cause injury to any person or entity. You further agree that no Comments submitted by you to our Website will be or contain libelous or otherwise unlawful, threatening, abusive or obscene material, or contain software viruses, bugs, worms, political campaigning, commercial solicitation, chain letters, mass mailings or any form of "spam".<br>
							We reserve the right (but not the obligation) to monitor and edit or remove any Comments submitted to our Website. You grant us the right to use the name that you submit in connection with any Comments. You undertake not to use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any Comments you submit. You are and shall remain solely responsible for the content of any Comments that you make and you agree to indemnify us and our affiliates for all claims resulting from any Comments you submit. We and our affiliates take no responsibility and assume no liability for any Comments submitted by you or any third party. </p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Ownership of Rights</b></div>
							<div class="collapsible-body"><p>All rights, including copyright, in this Website are owned by or licensed to us. Any use of this Website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without our permission. You are prohibited from modifying, copying, distributing, transmitting, displaying, printing, publishing, selling, licensing, creating derivative works or using any content available on or through our Website for commercial or public purposes. You may not modify, distribute or re-post something on this Website for any purpose.<br>
							The Site contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music, sound, and the entire contents of GetIITians protected by copyright as a collective work under the applicable copyright laws. GetIITians owns a copyright in the selection, coordination, arrangement and enhancement of such content, as well as copyright or license to use in the content original to it. You may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. You may download / print / save copyrighted material for your personal use only. Except as otherwise expressly stated under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material without the express permission of GetIITians is permitted. If copying, redistribution or publication of copyrighted material is permitted, no changes in or deletion of author attribution, trademark legend or copyright notice shall be made.<br>
							You acknowledge that you do not acquire any ownership rights by downloading copyrighted material. Trademarks that are located within or on our Website or a website otherwise owned or operated in conjunction with GetIITians shall not be deemed to be in the public domain but rather the exclusive property of GetIITians, unless such site is under license from the trademark owner thereof in which case such license is for the exclusive benefit and use of GetIITians, unless otherwise stated. <br>
							GetIItians does not hav any express burden responsibility to provide you with indications, markings or anything else that may aid you in determining whether the material in question is copyrighted or trademarked. You shall be solely liable for any damage resulting from any infringement of copyrights, trademark, proprietary rights or any other ham resulting from such a submission, By submitting materials to any public area of the Website, you warrant that the owner of such materials has expressly granted GetIITians the royalty-free, perpetual, irrevocable, non-exclusive, right and license to use, reproduce, modify, adapt, ,publish, translate, and distribute such materials (in whole or in part) worldwide and/or to incorporate it in other works in any form, media, technology now known or hereafter developed for the full-term of any copyright that may exist in such material. You also permit any other end user to access, view, store, or reproduce the material for that end user’s personal use. You hereby grant GetIITians, the right to edit, copy, publish and distribute any material made available on the Website by you.<br>
							If you come across any abuse or violation of these Terms, please report to info@getiitians.com.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Indemnity</b></div>
							<div class="collapsible-body"><p>You agree to defend, indemnify and hold us and our employees, directors, officers, agents and their successors and assigns, harmless from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of or relating to claims based upon your actions or inactions, which may result in any loss or liability to us or any third party, including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfilment of any of your obligations under these Terms of Use or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of these Terms of Use.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Termination And Survival of the Terms after the Term ends</b></div>
							<div class="collapsible-body"><p>GetIITians may terminate these Terms at any time. Without limiting the foregoing, GetIITians shall have the right to immediately terminate your password or account or block your IP address, in the event of any conduct by you, which GetIITians, in its sole discretion, considers to be unacceptable, or in breach of these Terms.<br>
							You may terminate these Terms at any time, provided that you discontinue any further use of our Website.<br>
							Notwithstanding any other provisions of these Terms, or any general legal principles to the contrary, any provision of these Terms that imposes or contemplates continuing obligations on a party including our right to any Comment will survive the expiration or termination of these Terms.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Limitation of Liability and Disclaimers</b></div>
							<div class="collapsible-body"><p>The Website is provided without any warranties or guarantees and in an "As Is" condition. You must bear the risks associated with the use of the Website.<br>
							We will not be responsible for any errors or omissions or for the results obtained from the use of such information or for any technical problems you may experience with the Website. This disclaimer does not apply to any product warranty offered by us as specified in the product specifications. This disclaimer constitutes an essential part of these Terms. To the fullest extent permitted under applicable law, we or our partners shall not be liable for any indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising out of or in connection with the Website, its services or these Terms. Without prejudice to the generality of the section above, our total liability to you for all liabilities arising out of these Terms, be it in tort or contract or any other legal theory is limited to the value of the product ordered by you.  We, our associates and technology partners make no representations or warranties about the accuracy, reliability, completeness, relevance and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of the Website or that the operation of the Website will be error free and/or uninterrupted. Consequently, GetIITians assumes no liability whatsoever for any monetary or other damage suffered by you on account of the delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the Website; and/or any interruption or errors in the operation of the Website.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Website Security</b></div>
							<div class="collapsible-body"><p>The Website is provided without any warranties or guarantees and in an "As Is" condition. You must bear the risks associated with the use of the Website.<br>
							We will not be responsible for any errors or omissions or for the results obtained from the use of such information or for any technical problems you may experience with the Website. This disclaimer does not apply to any product warranty offered by us as specified in the product specifications. This disclaimer constitutes an essential part of these Terms. To the fullest extent permitted under applicable law, we or our partners shall not be liable for any indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising out of or in connection with the Website, its services or these Terms. Without prejudice to the generality of the section above, our total liability to you for all liabilities arising out of these Terms, be it in tort or contract or any other legal theory is limited to the value of the product ordered by you.  We, our associates and technology partners make no representations or warranties about the accuracy, reliability, completeness, relevance and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of the Website or that the operation of the Website will be error free and/or uninterrupted. Consequently, GetIItians assumes no liability whatsoever for any monetary or other damage suffered by you on account of the delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the Website; and/or any interruption or errors in the operation of the Website.</p></div>
						</li>
						<li>
							<div class="collapsible-header center green-text text-darken-3"><b>Entire Terms</b></div>
							<div class="collapsible-body"><p>If any part of these Terms is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed to be superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Terms shall continue in effect. Unless otherwise specified herein, these Terms and the Website policies constitute the entire agreement between you and GetIITians with respect to our sites/services and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between you and us with respect to GetIITians. Our failure to act with respect to a breach by you or others does not waive our right to act with respect to subsequent or similar breaches.</p></div>
						</li>
					</ul>
				</div>
			</div>
		</div>

<?php
load_view("Template/footer.php",$inp);
load_view("Template/bottom.php",$inp);
?>